# === БАЗА ДАННЫХ (Внутренняя сеть Railway - самая надежная) ===
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=uyjLfRJwPfrECAaPqJHVOGycjYpEjUMs

# === HIBERNATE (Обязательно указываем диалект, чтобы избежать ошибки при запуске) ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === ИНИЦИАЛИЗАЦИЯ ДАННЫХ ===
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# === ПОРТ ===
server.port=${PORT:8080}