# === БАЗА ДАННЫХ ===
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/Logus}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:123}

# === HIBERNATE ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === ИНИЦИАЛИЗАЦИЯ ДАННЫХ ===
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# === ПОРТ ===
server.port=${PORT:8080}