# === БАЗА ДАННЫХ (ВРЕМЕННАЯ ПРЯМАЯ НАСТРОЙКА ДЛЯ ТЕСТА) ===
spring.datasource.url=jdbc:postgresql://db.ahmjnonuivkaschorydy.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Qwqwerty121!!12

# === HIBERNATE ===
spring.jpa.hibernate.ddl-auto=update
# Убираем явное указание диалекта, Spring определит его сам (как советует предупреждение в логе)

# === ИНИЦИАЛИЗАЦИЯ ДАННЫХ ===
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# === ПОРТ ===
server.port=${PORT:8080}